
### Service Health-Check Endpoint
GET http://127.0.0.1:5000/health HTTP/1.1





###GET ALL USERS
GET http://127.0.0.1:5000/users HTTP/1.1


###GET SINGLE USERS
GET http://127.0.0.1:5000/users/699f45c3e84a405d1afc786b HTTP/1.1


###GET ALL USERS IN COMPANY
GET http://127.0.0.1:5000/company/65f1c9b2a4d8c1a123456789/users HTTP/1.1

###CREATE NEW USER
POST http://127.0.0.1:5000/users HTTP/1.1
Content-Type: application/json

{
  "name": "shlomik ",
  "lastName": "zion",
  "phoneNumber": "+972501234227",
  "companyId": [
    "65f1c9b2a4d8c1a123456789"
  ],
  "role_id": "65f1c9b2a4d8c1a111111111",
  "userType": "Access",
  "email": "shlomik@example.com"
}

###DELETE USER BY ID
DELETE http://127.0.0.1:5000/users/1 HTTP/1.1


###UPDATE  USER
PUT http://127.0.0.1:5000/users/699f46a301d67aa6ed56d9a1 HTTP/1.1
Content-Type: application/json


{
  "name": "slomikkkkk ",
  "lastName": "ZIONMANNN",
  "phoneNumber": "+972501234227",
  "companyId": [
    "65f1c9b2a4d8c1a123456789"
  ],
  "role_id": "65f1c9b2a4d8c1a111111111",
  "userType": "Access",
  "email": "shlomik@example.com"
}

###Testing Creating Tenant
POST http://127.0.0.1:5000/tenant
Content-Type: application/json

{
  "tenantName": "Shlomi king",
  "buyerId": "65d9f8a1c4b2a7e91f0a1234"
}

###Testing Creating Tenant
PUT http://127.0.0.1:5000/tenant/699eb80a99e3b9a131c2adc4 HTTP/1.1
Content-Type: application/json

{
  "tenantName": "Shlomi king!123312!!",
  "buyerId": "65d9f8a1c4b2a7e91f0a4321"
}
###GET TENANTS
GET http://127.0.0.1:5000/tenants HTTP/1.1

###GET TENANTS
GET http://127.0.0.1:5000/tenant/699eb397c5e6f3ab9b4c2a84 HTTP/1.1

###GET COMPANIES
GET http://127.0.0.1:5000/companies HTTP/1.1

###GET COMPANY
GET http://127.0.0.1:5000/company/699edc324180dd60cad1a960 HTTP/1.1

###CREATE COMPANY:
POST http://127.0.0.1:5000/company HTTP/1.1
Content-Type: application/json

{
  "companyIndustryId": "64f4b0e2a8f2c1d234567891",
  "companyName": "COMOBOBOBOB Cyber",
  "tenantId": "64f4b0e2a8f2c1d234567890",
  "country": "Israel",
  "language": "Hebrew"
}

###GET TENANT COMPANIES:
GET http://127.0.0.1:5000/company/tenant/64f4b0e2a8f2c1d234567890 HTTP/1.1



###UPDATE COMPANY:
PUT http://127.0.0.1:5000/company/699edbda2ea1d4ce8fe4a80C HTTP/1.1
Content-Type: application/json

{
    "tenantId": "64f4b0e2a8f2c1d234511111"

}

# {
#     "_id": "699ef1cb54d08abdac52410f",
#     "tenantId": "64f4b0e2a8f2c1d234567890",
#     "companyName": "Shlomi king TEST",
#     "companyIndustryId": "64f4b0e2a8f2c1d234567891",
#     "companyWebsiteUrl": "https://www.globaltech123123.com",
#     "country": "Israel",
#     "language": "Hebrew",
#     "createdAt": "2026-02-25T12:57:47.613Z",
#     "updatedAt": "2026-02-25T12:57:47.613Z"
#   }


###GET INDUSTRIES:
GET http://127.0.0.1:5000/industries HTTP/1.1


###CREATE INDUSTRY:
POST http://127.0.0.1:5000/industry HTTP/1.1
Content-Type: application/json

{
  "industryName": "MY MAN333333",
  "exposureCategories": [
    "642e9f5f1a2c3b001234abcd",
    "642e9f5f1a2c3b001234abce",
    "642e9f5f1a2c3b001234abcf"
  ]
}


###update INDUSTRY:
PUT http://127.0.0.1:5000/industry/699f162ff38a0b221dc1af24 HTTP/1.1
Content-Type: application/json

{
  "industryName": "MY MAN333333",
  "exposureCategories": [
    "642e9f5f1a2c3b001234bbbb",
    "642e9f5f1a2c3b001234bbbb",
    "642e9f5f1a2c3b001234bbbb"
  ]
}

    # "_id": "699f162ff38a0b221dc1af24",
    # "industryName": "MY MAN2",
    # "exposureCategories": [
    #   "642e9f5f1a2c3b001234abcd",
    #   "642e9f5f1a2c3b001234abce",
    #   "642e9f5f1a2c3b001234abcf"
    # ],
    # "createdAt": "2026-02-25T15:33:03.864Z",
    # "updatedAt": "2026-02-25T15:33:03.864Z"




###GET EXPOSURE CATEGORIES:
GET http://127.0.0.1:5000/exposure-categories HTTP/1.1

###CREATE EXPOSURE CATEGORY:
POST http://127.0.0.1:5000/exposure-category HTTP/1.1
Content-Type: application/json

{
  "companyId": "642e9f5f1a2c3b001234abcd",
  "categoryName": "Data Privacy23231",
  "risks": [
    "642e9f5f1a2c3b001234abcf",
    "642e9f5f1a2c3b001234abd0"
  ],
  "exposureCategoryWeight": 7
}


###UPDATE EXPOSURE CATEGORY:
PUT http://127.0.0.1:5000/exposure-category/699f20c1e1f2306691621936 HTTP/1.1
Content-Type: application/json

{
  "companyId": "642e9f5f1a2c3b001234abcd",
  "categoryName": "DATA PRIVACY UPDATED",
  "risks": [
    "642e9f5f1a2c3b001234abcf"
  ],
  "exposureCategoryWeight": 8
}

# "_id": "699f20c1e1f2306691621936",
#     "companyId": "642e9f5f1a2c3b001234abcd",
#     "categoryName": "Data Privacy",
#     "risks": [
#       "642e9f5f1a2c3b001234abcf",
#       "642e9f5f1a2c3b001234abd0"
#     ],
#     "exposureCategoryWeight": 7,
#     "createdAt": "2026-02-25T16:18:09.956Z",
#     "updatedAt": "2026-02-25T16:18:09.956Z"



###Get Roles
GET http://127.0.0.1:5000/roles HTTP/1.1

###Get Roles By Industry
GET http://127.0.0.1:5000/roles/industry/642e9f5f1a2c3b001234abde

###Get Role
GET http://127.0.0.1:5000/roles/699f67953f7d2cbec6211bb9

###Create Role
POST http://127.0.0.1:5000/roles HTTP/1.1
Content-Type: application/json

{
  "companyId": "642e9f5f1a2c3b001234abdd",
  "industryId": "642e9f5f1a2c3b001234abde",
  "roleName": "Risk Analyst",
  "roleDescription": "Assesses and monitors potential risks within the company.",
  "exposureCategories": "642e9f5f1a2c3b001234abdf",
  "roleRisks": [
    "642e9f5f1a2c3b001234abe0",
    "642e9f5f1a2c3b001234abe1",
    "642e9f5f1a2c3b001234abe2"
  ]
}

###Update Role
PUT http://127.0.0.1:5000/roles/699f67953f7d2cbec6211bb9 HTTP/1.1
Content-Type: application/json

{
  "companyId": "642e9f5f1a2c3b001234abdd",
  "industryId": "642e9f5f1a2c3b001234abde",
  "roleName": "Risk Analyst THE BESTTT",
  "roleDescription": "Assesses and monitors potential risks within the company.",
  "exposureCategories": "642e9f5f1a2c3b001234abdf",
  "roleRisks": [
    "642e9f5f1a2c3b001234abe0",
    "642e9f5f1a2c3b001234abe1",
    "642e9f5f1a2c3b001234abe2"
  ]
}




###Get Risks
GET http://127.0.0.1:5000/risks HTTP/1.1

###Get Risk By Exposure Category
GET http://127.0.0.1:5000/risks/exsposure-category/642e9f5f1a2c3b001234abcd

###Get Risk
GET http://127.0.0.1:5000/risks/699f7667e24088d9be84f059

###Create Risk
POST http://127.0.0.1:5000/risks HTTP/1.1
Content-Type: application/json

{
  "riskName": "System Downtime Risk",
  "exposureCategoryId": "642e9f5f1a2c3b001234abdd",
  "exposureRiskWeight": 8.2,
  "tasks": [
    "642e9f5f1a2c3b001234abe1",
    "642e9f5f1a2c3b001234abe2",
    "642e9f5f1a2c3b001234abe3",
    "642e9f5f1a2c3b001234abe4"
  ],
  "createdAt": "2026-02-26T11:30:00Z",
  "updatedAt": "2026-02-26T11:30:00Z"
}

###Update Risk
PUT http://127.0.0.1:5000/risks/699f7694e24088d9be84f060 HTTP/1.1
Content-Type: application/json

{
  "riskName": "System Downtime Risk!!!!!!!!!!!",
  "exposureCategoryId": "642e9f5f1a2c3b001234abcd",
  "exposureRiskWeight": 8.5,
  "tasks": [
    "642e9f5f1a2c3b001234abe1",
    "642e9f5f1a2c3b001234abe1",
    "642e9f5f1a2c3b001234abe1",
    "642e9f5f1a2c3b001234abe1"
  ],
  "createdAt": "2026-02-26T11:30:00Z",
  "updatedAt": "2026-02-26T11:30:00Z"
}

  # },
  # {
  #   _id: ObjectId('699f7694e24088d9be84f060'),
  #   riskName: 'System Downtime Risk',
  #   exposureCategoryId: ObjectId('642e9f5f1a2c3b001234abdd'),
  #   tasks: [
  #     ObjectId('642e9f5f1a2c3b001234abe1'),
  #     ObjectId('642e9f5f1a2c3b001234abe2'),
  #     ObjectId('642e9f5f1a2c3b001234abe3'),
  #     ObjectId('642e9f5f1a2c3b001234abe4')
  #   ],
  #   exposureRiskWeight: 8.2,
  #   createdAt: ISODate('2026-02-25T22:24:20.399Z'),
  #   updatedAt: ISODate('2026-02-25T22:24:20.399Z'),
  #   __v: 0
  # }